services:
  server:
    build:
      context: .
    env_file:
      - .env
    environment:
      NODE_ENV: production
      CORS_ORIGINS: ${CORS_ORIGIN}
      REDIS_HOST: shared_redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DB_HOST: shared_mysql
      DB_PORT: ${DB_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: unless-stopped
    networks:
      - infrastructure_network 

networks:
  infrastructure_network:
    external: true